### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by hugofpaiva** [isabyr/frame_timestamp#3]
Is there any possibility of moving to Python? Or maybe with a wrapper 🤔
It would be very useful for later analysis of the images on Yolo

**Comment by isabyr** [comment]
Unfortunately FFMpeg does not provide built-in methods for wrapping and I don't have much free time for now. The best I can do right now is to containerize ffmpeg and pass decoded frames with ZMQ. But I'm not sure about the throughput, decoded FULLHD YUV frame is 3MB, with 30fps it would be ~100MB/sec. Let me know if this suits you.

**Comment by hugofpaiva** [comment]
Yes, it suits!
Thanks! :)

**Comment by hugofpaiva** [comment]
Thanks for the help. I no longer need it and since you are busy, I will close the issue.
Sorry for the inconvenience...
