### ISSUE TITLE
Question: How is the offset 2208988800 derived?

### ISSUE THREAD

**Issue by grantwilk** [isabyr/frame_timestamp#5]
Hello,

Trying to read through and understand this implementation so I can use it for a project. Out of curiosity, how did you derive the constant `2208988800` that is used in the following line of code from this example?

```
uint32_t seconds = ((last_ntp_time >> 32) & 0xffffffff)-2208988800;
```

Thanks!

**Comment by isabyr** [comment]
Hi,

It is a NTP to UNIX timestamp conversion [formula](https://stackoverflow.com/a/29138806/1665791), difference between 1900 and 1970 in seconds

**Comment by grantwilk** [comment]
Ahhh that makes sense. Thank you for your quick response! Much appreciated.
